# Syntax:: https://docs.gitlab.com/ee/ci/yaml/index.html

stages:
    - build
    - release

default:
    image: node:14.17.6

cache:
    paths:
        - node_modules/

builder:
    stage: build
    only:
        refs:
            - main
    variables:
        PUBLIC_URL: /
    script:
        - npm i
        - npm run build
    cache:
        paths:
            - node_modules/
    artifacts:
        paths:
            - dist/
            - node_modules/


create-release:
    stage: release
    only:
        refs:
            - main
    before_script:
        - git --version
        - git config --global user.name "${GITLAB_USER_NAME}"
        - git config --global user.email "${GITLAB_USER_EMAIL}"
        - echo "$GITLAB_USER_EMAIL"
        - echo "$GITLAB_USER_NAME"
        - echo "$GITLAB_TOKEN"
    variables:
        GITLAB_TOKEN: $GITLAB_TOKEN
    script:
        - npx semantic-release